services:
  postgres:
    image: postgres:16-alpine
    container_name: ecobite_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecobite
      POSTGRES_USER: ecobite_user
      POSTGRES_PASSWORD: ecobite_pass
    ports:
      - "5432:5432"
    volumes:
      - ecobite_pg_data:/var/lib/postgresql/data

volumes:
  ecobite_pg_data: